### ISSUE TITLE
Handle optional value

### ISSUE THREAD

**Issue by norbertpy** [jamesmcnamara/shades#22]
This is awesome. Specially the typing is fantastic. Just a quick question `partial.lenses` has a handy function [valueOr](https://github.com/calmm-js/partial.lenses#l-valueor) for supplying a default value when it doesn't exist. Is there a similar thing for `shades`?

I looked through the `optional` and `maybe` in the repo but couldn't find anything as API.

```typescript
interface Fruit {
   title?: string;
   count: number;
}

let f: Fruit = { count: 12 };
S.get('title')(f); // ?????
```

**Comment by jamesmcnamara** [comment]
This is a really good question. 

Handling optional values has consistently been a tricky thing to do with this library; let me experiment with some stuff and see if I can figure out an idiomatic way to do this.

**Comment by jamesmcnamara** [comment]
Sorry for the delay @norbertpy, I've been traveling in Bolivia and mostly away from my computer.

Also sorry for the length of this message, I'm a pretty chatty fellow.

Let's use a cyclical type so that we can we get weird:
```ts
interface Friend {
  name: string;
  bestFriend?: Friend;
}

const norbert: Friend = { name: 'Norbert' }
const james: Friend = { name: 'james' }
```

First off I thought about doing some kind of optional lens modifier that would let you fill in the value in the lens; something like:
```ts
> get(maybeOr('bestFriend', norbert), 'name')(james)
'Norbert'
```

However this faces two downsides:

1. It's syntactically clunky. Vain as it is, I like to keep shades pretty.
2. It would have to be a special case for `get`

Number two is the killer. All of the `get`, `mod`, and `set` functions work just by having overloads for every number of inputs (up to 6) of every possible combination of possible lens input: `string`, `number`, `Traversal`, and `Lens`. Adding a 5th type is quite an exponential blow up (shades already has more lines of typings then lodash).

So I think a better solution, at least for now, is to fill in the values at the value level BEFORE they are passed to a lens. This can be done with the new function [`fill`](https://github.com/jamesmcnamara/shades/blob/master/README.md#fill).

`fill` is just a merge function but it updates the output type to reflect which fields were filled.
```ts
get('bestFriend')(norbert) // Friend | undefined
get('bestFriend', 'name')(norbert) // ErrorCannotLensIntoOptionalKey<Friend | undefined, "name">

const areFriends = fill({bestFriend: james})(norbert)
areFriends.bestFriend // Friend
get('bestFriend', 'name')(areFriends) // string
```

This also works if you want to fill in multiple nested relationships:
```ts
const deepFriends = fill({bestFriend: areFriends})(norbert)
get('bestFriend', 'bestFriend', 'name')(deepFriends) // string
```

What do you think? All of this is available on a new beta, you can just `npm install shades@beta` to play with it.

P.S. This commit also solves another issue that existed where if you lensed through optional fields, it would just assume that the fields were there. Now you get a `ErrorCannotLensIntoOptionalKey<Friend | undefined, "name">` type as an error indicator.

**Comment by norbertpy** [comment]
Hey, first of all you're awesome already. You don't have to be sorry for an open source issue being late. I admire the fact that you even replied to my question. 

Secondly, `fill` seems like a very nice addition. Let me give that a try and I'll report back.

**Comment by norbertpy** [comment]
One problem with `fill`, which as you said is just a merge function, is it updates the value no matter what. 

```javascript
shades> fill({ hey: 'm' })({})
// => { hey: 'm' }
shades> fill({ hey: 'm' })({ hey: 'asd' })
// => { hey: 'm' }
```

`valueOr` on the other hand, is only applied if the value is `undefined` or `null`. I guess my use case is, I have some deeply nested structure that I don't know if they have such a value or not.

 - When I `get`, I'd like to get a default value. Otherwise the `get` typing doesn't even let me create a lens on an optional property
 - When I `mod`, I want to only apply the `oldValue => fn(oldValue) /* newValue` /*` if there is a non-null value.

Like:

```javascript
get('first', 'second', 'third', all(), 'blah', valueOr('my-default'))(o)
```

**Comment by jamesmcnamara** [comment]
You raise an interesting point. 

To the first point, I've pushed a new beta that does a deep merge of the two values, always showing preference to the provided value:
```ts
shades> fill({a: {b: 10, c: 20}})({a: {c: 30}})
{a: {b: 10, c: 30}}
```

But you are right that with deeply nested objects it gets repetitive, and there is no great solution for Traversals. I will look into adding a 5th type of lens when I have some time and see how much complexity it adds to the typings.

In the meantime you should be able to do something like this:
```ts
interface A {
  first: {
    second: {
      third: B[];
    }
  }
}

interface B {
  blah?: string;
}

const out = get('first', 'second', 'third')(o)
const thisHasTheRightType = out.map(fill({blah: 'my-default'})
```
Definitely messier but it does work. And your `mod` example is even cleaner:

```ts
const ifDefined = <A, F extends (a: A) => A>(fn: F) => (x?: A) => x === undefined || x === null ? x : fn(x)

mod('first', 'second', 'third', all(), 'blah')(ifDefined(myUpdater))(o)
```

**Comment by jamesmcnamara** [comment]
This is honestly kind of funny to me, but after starting to think about what an implementation of this would look like, I realized it's already possible thanks to [Virtual Lenses](https://github.com/jamesmcnamara/shades#virtual-lenses). It kind of amazes me that this library can do things that even I don't realize it's capable of.

All you want is something that will take the focus of the lens and transform it from optional to guaranteed, so you can easily write a lens that will do that.

```ts
import { Lens } from 'shades'

const valueOr = <T>(dflt: T): Lens<T | undefined, T> => ({
  get: val => val || dflt,
  mod: fn => val => fn(val || dflt)
})

get('first', 'second', 'third', all(), 'blah', valueOr('my-default'))(o)
```

This does not have the `mod` behavior you described though; that behavior would be aberrant from everything else. If you want that, you can use the `ifDefined` approach described above.

P.S. Even though you can easily write `valueOr` yourself outside of the library, I think it's such a nice pattern that I added one with slightly tighter edge-case checking to the [beta](https://github.com/jamesmcnamara/shades#valueor)

**Comment by norbertpy** [comment]
Wow James, I think I should have read the docs more carefully. With this, I can write whatever lens I want. Wohoo, thanks a lot.

**Comment by jamesmcnamara** [comment]
Hahaha don't worry, if I didn't realize that this was possible, I wouldn't expect anyone reading the docs to.
