### ISSUE TITLE
`fill` not working well with generics

### ISSUE THREAD

**Issue by jethrolarson** [jamesmcnamara/shades#41]
```typescript
const fillFoo = <T extends {foo?: boolean}>(bar: T): T => fill({foo: true})(bar);
```
```
Type 'Fill<T, { foo: boolean; }>' is not assignable to type 'T'.
  'Fill<T, { foo: boolean; }>' is assignable to the constraint of type 'T', but 'T' could be instantiated with a different subtype of constraint '{ foo?: boolean | undefined; }'.ts(2322)
```
Shades: 2.1.0
TS: 3.8.2 strict

**Comment by jamesmcnamara** [comment]
Very late reply but it seems the issue is not that it can't handle generics, but that the return type of `fillFoo` is not `T` it's `Fill<T, {foo: true}>` which has a more refined type than the input. If you really want to lose that type refinement you can just add an `as T` at the end, i.e.:
```ts
const fillFoo = <T extends {foo?: boolean}>(bar: T): T => fill({foo: true})(bar) as T;
```
But that is a bit silly because the point of `fill` is to assert to they type system that certain values are present.
