### ISSUE TITLE
TypeScript support?

### ISSUE THREAD

**Issue by enisdenjo** [jamesmcnamara/shades#9]
First of all, I think that shades are **super awesome**! I am still not using it, but reading through the docs got my heart racing...

The reason why I am not using it is because of TS support, any plan on adding it?

Thanks in advance!

**Comment by jamesmcnamara** [comment]
Thanks so much! I'm glad you're excited.

It does not support TS as of now because it uses a few stage-0 features which I'm not sure are supported in the TypeScript compiler.

That said I do have a flow module declaration file for it which I would be happy to include.

I've never worked with TS, but I'll see if I can get a small project up and running, and see what changes are required to get this supported (any input or pointers would be helpful).

However, one failing is that this library is pretty dependently-typed (pass an object get an object back, pass a list get a list back), so type declarations tend to be littered with `any`

**Comment by jamesmcnamara** [comment]
And any PR's are always welcome :)

**Comment by enisdenjo** [comment]
Yap, I figured. Since you use string paths (ex. `'some.path.to'`) for extraction, it would be hard for a type interpreter to figure out the correct result (or even make autocomplete suggestions).

Maybe we pass the return type to the function? (the following code is in TS, but TS & flow are quite similar)
```ts
interface IObject {
  some: {
    path: {
      to: {
        a: string;
      };
    };
  };
}

const object: IObject = {
  some: {
    path: {
      to: {
        a: 'value',
      },
    },
  },
};

const result = get<IObject['some']['path']['to']['a'] | undefined | null>('some.path.to.a')(object);
```

Which will be interpreted correctly, but its feels like overloading... As far as I've seen, to accomplish having a correct return type, sadly, you must overload. (like in `loadsh.get` typings). But overloading does not work for shades, only if we use multiple arguments instead of a string path. (`get('some.path.to.a')` -> `get('some', 'path', 'to', 'a')`), but this might work? Maybe for typings you must use the `args` way?

What do you think? Maybe make helper `types` which will make this code look nicer?

I'll be happy to make some PR's, but since its a very effective library I would prefer having a super nice typing implementation over a hacky one, if you get what I mean. 😄

**Comment by jamesmcnamara** [comment]
So first off the good news:
The current implementations of `get`, `set`, and `mod` already support multiple string arguments, so we could type a limited subset of the acceptable operations (through overloading):
```typescript
declare function get<
    S1,
    K1 extends keyof S1,
    K2 extends keyof S1[K1]
    >
    (lens: K1, lens2: K2): (obj: S1) => S1[K1][K2]
```
If we make it so that number literals are lenses into array indices (which I feel is a pretty natural syntax), we can actually type check things like `get('foo', 1, 'a')` by putting (somewhat hacky) constraints on `S1`:
```typescript

declare function get<
    S1 extends { [P in K1]: Array<S1[P][0]> },
    K1 extends keyof S1,
    K2 extends keyof S1[K1][0]>
    (lens1: K1, idx: number, lens2: K2): (obj: S1) => S1[K1][0][K2]
```

What's cool is that by using that same constraint trick, we can actually type traversals:
```typescript
interface User {
    posts: Post[]
}

interface Post {
    likes: number,
}

const user: User = {
    posts: [
        {
            likes: 10,
        }
    ]
}

interface Traversal<S> {}

declare function matching<S>(pred: (focus: S) => boolean): Traversal<S>

declare function get<
    S1 extends { [P in K1]: Array<S1[P][0]> },
    K1 extends keyof S1,
    K2 extends keyof S1[K1][0]>
    (lens1: K1, traversal: Traversal<S1[K1][0]>, lens2: K2): (obj: S1) => S1[K1][0][K2][]

// Typechecks!
get('posts', matching(p => p.likes > 10), 'likes') as (user: User) => number[]
```
The bad news is that some common patterns can't type check. Obviously dotted or bracketed paths won't be understood (`a.b[3].c`). Also dynamic paths won't work, i.e.:
```js
const pathIdx = 3
get('foo', pathIdx, 'bar')
```

My instinct is that we should generate a pile of overloaded typings for `get`, `set`, and `mod` that only allow the subset behaviors and type them. However we should provide an escape hatch for times when you need the dynamic behavior, something like 
```typescript
get.unsafe<Post>('users', userIdx, 'posts', postIdx)
```

How does that sound? Any pitfalls jump out at you? (I'm one day into my typescript career so I don't know if this is going to be problematic)

**Comment by enisdenjo** [comment]
Very interesting approach! I must say, I am a newbie to TypeScript too, but this sounds promising. I will play around with the code and see what we can accomplish as soon as I am able to, as I have some other work related stuff to handle.

But I am eager to play aroung with this! 😄

**Comment by enisdenjo** [comment]
Hey @jamesmcnamara,

So I've invested some time in thinking about typings. I've figured out the following:

```ts
```

**Comment by enisdenjo** [comment]
Hey @jamesmcnamara,

I've invested some time in thinking about the typings, this is what I came up with:
```ts
/**
 *
 * Definitions
 *
 */

// Core types
type Val<V> = V | undefined | null; // simply wraps the value to be itself, undefined or null. (helps avoid redundancy)
type Obj<K extends string, V> = Val<{[key in K]: Val<V>}>; // `any[K] = V`

// Overload "Obj"
/**
 * NOTE: notice when adding depth to "Obj" I always define the first depth (K1)
 * explicitly like so: `{[key1 in K1]: Obj<K2, V>}` instead of using: `Obj<K1, Obj<K2, V>>`.
 * The second way is technically correct, but for some reason is not typed correctly by TS, it
 * always returns `Val<{}>` insted of the correct object type definition. Bug?
 */
type Obj2<K1 extends string, K2 extends string, V> = Val<{[key1 in K1]: Obj<K2, V>}>;
type Obj3<K1 extends string, K2 extends string, K3 extends string, V> = Val<{[key1 in K1]: Obj2<K2, K3, V>}>;
type Obj4<K1 extends string, K2 extends string, K3 extends string, K4 extends string, V> = Val<{[key1 in K1]: Obj3<K2, K3, K4, V>}>;

// Overload "get"
/**
 * NOTE: since we are using currying, we cant define the object in the first
 * function of `get`. It simply does not work with TS, but it is also reasonable
 * since the object does not need to be defined immediately. You can, for example,
 * set the path to a nested value, but not pass the object right away. Performing
 * type check this way makes more sense, where if you pass a path and pass an
 * object later on which DOES NOT have that value, the object will be erroneous instead of
 * the path. Example below...
 */
function get<K1 extends string>(key1: K1): <V>(obj: Obj<K1, V>) => Val<V>;
function get<K1 extends string, K2 extends string>(key1: K1, key2: K2): <V>(obj: Obj2<K1, K2, V>) => Val<V>;
function get<K1 extends string, K2 extends string, K3 extends string>(key1: K1, key2: K2, key3: K3): <V>(obj: Obj3<K1, K2, K3, V>) => Val<V>;
function get<K1 extends string, K2 extends string, K3 extends string, K4 extends string>(key1: K1, key2: K2, key3: K3, key4: K4): <V>(obj: Obj4<K1, K2, K3, K4, V>) => Val<V>;
function get(...keys: string[]) {
  return (obj: any): any => {
    /* logic goes here... */
    return null;
  };
}

/**
 *
 * Examples
 *
 */

const testObj = {
  path: {
    to: {
      str: 'string',
      bool: false,
      num: 0,
      obj: {
        str: 'string',
      },
    },
  },
};

const testObj2 = {
  some: {
    other: {
      path: {
        str: 'string',
        bool: false,
        num: 0,
        obj: {
          str: 'string',
        },
      },
    },
  },
};

// works with dynamic paths!
const k1 = 'path';
const k3 = 'obj';

const val = get(k1, 'to', k3)(testObj); // no errors
const val2 = get(k1, 'to', k3)(testObj2); // error on `testObj2` because the path to the value is not correct!

// val can be (null || undefined)
if (val) {
  // tslint:disable-next-line no-console
  console.log(val.str /* correct type! */);
}
```

It is still missing some parts (like traversals, numerical keys, passing arrays)... But as soon as I have more free time, I'll continue the implementation.

What do you think?

**Comment by jamesmcnamara** [comment]
Almost 8 months later, but I just put out a beta with typescript support!

If you get a chance to play with it, that would be awesome, I'd love to find some bugs.

You can install it with:
```sh
npm i shades@beta
```
